"""empty message

Revision ID: b8642696f7fb
Revises: cacbdb72f8d8
Create Date: 2025-03-29 00:41:39.859390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8642696f7fb'
down_revision = 'cacbdb72f8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('Pending', 'Successful', 'Canceled', name='statusenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('Pending', 'Successful', 'Canceled', name='statusenum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
