"""empty message

Revision ID: f8b4905995ac
Revises: 3a615304a9a8
Create Date: 2025-03-28 20:56:12.560985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b4905995ac'
down_revision = '3a615304a9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=False))

    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=False))

    with op.batch_alter_table('ticketorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_active', sa.Integer(), nullable=False))
        batch_op.drop_column('ticket_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticketorders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_status', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('ticket_active')

    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
